# Central configuration for paths and schema

paths:
  inputs_root: inputs
  outputs_root: outputs
  forecasts: outputs/forecasts
  evaluation: outputs/evaluation
  processed: outputs/processed
  interim: outputs/interim
  reference: inputs/reference

submission:
  required_columns:
    - Country1
    - Country2
    - ProductCode
    - TradeFlow
    - Value
  trade_flow_values: [Export, Import]
  country_code_len: 3
  product_code_len: 4

evaluation:
  metric: smape

