# Central configuration for paths and schema

paths:
  # Input directories
  inputs_root: inputs
  raw: inputs/raw
  external: inputs/external
  reference: inputs/reference
  
  # Output directories
  outputs_root: outputs
  interim: outputs/interim
  processed: outputs/processed
  forecasts: outputs/forecasts
  evaluation: outputs/evaluation
  reports: outputs/reports

submission:
  required_columns:
    - Country1
    - Country2
    - ProductCode
    - TradeFlow
    - Value
  trade_flow_values: [Export, Import]
  country_code_len: 3
  product_code_len: 4

evaluation:
  metric: smape

# Data processing configuration
data_processing:
  # Minimum number of unique HS4 products per country-month
  min_products: 200
  
  # HS4 code mapping file
  hs4_codes_file: code_hs4.xlsx
  
  # Economic indicators files
  indicators_file: df_long.csv
  reer_file: EER_COUNTRIES.csv
  
  # Date range for external data
  start_date: "2022-12-31"
  end_date: "2024-11-30"
  
  # Comtrade years to process
  comtrade_years: [2021, 2022, 2025]
  
  # FRED API configuration (set via environment variable)
  # FRED_API_KEY: "your_api_key_here"

# Model configuration
model:
  # Features to use for modeling
  feature_categories:
    - temporal  # month_id, time-based features
    - categorical  # country_id, product_id_hs4, trade_flow_name
    - economic  # GDP, REER, etc.
    - commodity  # commodity prices
    - exchange_rate  # currency exchange rates
  
  # Target variable
  target: trade_value
  
  # Train/validation split
  validation_months: 6  # Use last N months for validation
  
  # Model types to try
  algorithms:
    - RandomForest
    - GradientBoosting
    - XGBoost
    - LightGBM
    - CatBoost

